# main menu
[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "How It Works"
url = "how-it-works/"
weight = 3

[[main]]
name = "Services"
url = "services/"
weight = 4
  
[[main]]
name = "Contact"
url = "contact/"
weight = 6
  
[[main]]
name = "Pages"
weight = 7
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Blog"
  url = "blog/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Service Details"
  url = "services/service-1/"
  weight = 3

  [[main]]
  parent = "Pages"
  name = "FAQ's"
  url = "faq/"
  weight = 4

  [[main]]
  parent = "Pages"
  name = "Elements"
  url = "blog/elements/"
  weight = 5

  [[main]]
  parent = "Pages"
  name = "Legal"
  url = "legal/"
  weight = 6

  [[main]]
  parent = "Pages"
  name = "Terms & Condition"
  url = "terms/"
  weight = 7

  [[main]]
  parent = "Pages"
  name = "Privacy & Policy"
  url = "privacy-policy/"
  weight = 8


################################### Footer Menu #####################################
[[footer]]
name = "Terms & Conditions"
url = "/terms"

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"



[[about]]
name = "Our Story"
url = "/our-story"

[[about]]
name = "Benefits"
url = "/benefits"

[[about]]
name = "Team"
url = "/team"

[[about]]
name = "Careers"
url = "/careers"



[[help]]
name = "FAQs"
url = "/faq"

[[help]]
name = "Contact Us"
url = "/contact"